project:
  type: website
  output-dir: docs/

website:
  title: "Vriendenvlag"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      - vlag_animatie.html




