project:
  type: website
  output-dir: docs/

website:
  title: "Vriendenvlag"
  navbar:
    background: transparent
    left:
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      - animejs.html




